In [1]:
from sklearn.svm import SVC
from sklearn import svm
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import warnings 
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
data=pd.read_csv('glass.csv')
data.head()

Id       RI     Na    Mg    Al    Si      K    Ca   Ba   Fe  Type
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [3]:
x=data.drop('Type',axis=1)
y=data.Type

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state = 101)

In [5]:
model1=SVC(kernel='sigmoid')
model2=SVC(kernel='poly')
model3=SVC(kernel='rbf')

In [6]:
model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)

SVC()

In [7]:
y_pred1=model1.predict(x_test)

In [8]:
y_pred2=model2.predict(x_test)

In [9]:
y_pred3=model3.predict(x_test)

In [10]:
print("Evaluation of Model 1 Sigmoid: ")
print(confusion_matrix(y_test,y_pred1))
print(classification_report(y_test,y_pred1))

Evaluation of Model 1 Sigmoid: 
[[14  4  0  0  0  0]
 [ 0 10  0  0  0  0]
 [ 0  6  0  0  0  0]
 [ 0  4  0  0  0  0]
 [ 0  2  0  0  0  0]
 [ 0  3  0  0  0  0]]
              precision    recall  f1-score   support

           1       1.00      0.78      0.88        18
           2       0.34      1.00      0.51        10
           3       0.00      0.00      0.00         6
           5       0.00      0.00      0.00         4
           6       0.00      0.00      0.00         2
           7       0.00      0.00      0.00         3

    accuracy                           0.56        43
   macro avg       0.22      0.30      0.23        43
weighted avg       0.50      0.56      0.49        43



In [11]:
print("Evaluation of Model 2 Polynomial: ")
print(confusion_matrix(y_test,y_pred2))
print(classification_report(y_test,y_pred2))

Evaluation of Model 2 Polynomial: 
[[18  0  0  0  0  0]
 [ 0 10  0  0  0  0]
 [ 0  0  6  0  0  0]
 [ 0  0  0  4  0  0]
 [ 0  0  0  0  1  1]
 [ 0  0  0  0  0  3]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        10
           3       1.00      1.00      1.00         6
           5       1.00      1.00      1.00         4
           6       1.00      0.50      0.67         2
           7       0.75      1.00      0.86         3

    accuracy                           0.98        43
   macro avg       0.96      0.92      0.92        43
weighted avg       0.98      0.98      0.97        43



In [12]:
print("Evaluation of Model 3 RBF: ")
print(confusion_matrix(y_test,y_pred3))
print(classification_report(y_test,y_pred3))

Evaluation of Model 3 RBF: 
[[17  1  0  0  0  0]
 [ 0 10  0  0  0  0]
 [ 0  6  0  0  0  0]
 [ 0  1  0  0  0  3]
 [ 0  0  0  0  0  2]
 [ 0  0  0  0  0  3]]
              precision    recall  f1-score   support

           1       1.00      0.94      0.97        18
           2       0.56      1.00      0.71        10
           3       0.00      0.00      0.00         6
           5       0.00      0.00      0.00         4
           6       0.00      0.00      0.00         2
           7       0.38      1.00      0.55         3

    accuracy                           0.70        43
   macro avg       0.32      0.49      0.37        43
weighted avg       0.57      0.70      0.61        43

