In [1]:
!python --version

Python 3.7.12


In [2]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn import svm
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [3]:
df = pd.read_csv('./glass.csv')
df.head()

Id       RI     Na    Mg    Al    Si      K    Ca   Ba   Fe  Type
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [4]:
x = df.drop('Type', axis=1)
y = df['Type']

In [5]:
x

Id       RI     Na    Mg    Al    Si      K    Ca    Ba   Fe
0      1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0
1      2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0
2      3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0
3      4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0
4      5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0
..   ...      ...    ...   ...   ...    ...   ...   ...   ...  ...
209  210  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0
210  211  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0
211  212  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0
212  213  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0
213  214  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0

[214 rows x 10 columns]

In [6]:
y

0      1
1      1
2      1
3      1
4      1
      ..
209    7
210    7
211    7
212    7
213    7
Name: Type, Length: 214, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = 101)

In [8]:
model1 = SVC(kernel='sigmoid')
model2 = SVC(kernel='poly')
model3 = SVC(kernel='rbf')

In [9]:
model1.fit(x_train, y_train)
model2.fit(x_train, y_train)
model3.fit(x_train, y_train)

SVC()

In [10]:
y_pred1 = model1.predict(x_test)
y_pred2 = model2.predict(x_test)
y_pred3 = model3.predict(x_test)

In [11]:
print("Evaluation of Model 1 Sigmoid: ")
print(confusion_matrix(y_test, y_pred1))
print(classification_report(y_test, y_pred1))

Evaluation of Model 1 Sigmoid: 
[[14  4  0  0  0  0]
 [ 0 10  0  0  0  0]
 [ 0  6  0  0  0  0]
 [ 0  4  0  0  0  0]
 [ 0  2  0  0  0  0]
 [ 0  3  0  0  0  0]]
              precision    recall  f1-score   support

           1       1.00      0.78      0.88        18
           2       0.34      1.00      0.51        10
           3       0.00      0.00      0.00         6
           5       0.00      0.00      0.00         4
           6       0.00      0.00      0.00         2
           7       0.00      0.00      0.00         3

    accuracy                           0.56        43
   macro avg       0.22      0.30      0.23        43
weighted avg       0.50      0.56      0.49        43



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [12]:
print("Evaluation of Model 2 Polynomial: ")
print(confusion_matrix(y_test, y_pred2))
print(classification_report(y_test, y_pred2))

Evaluation of Model 2 Polynomial: 
[[18  0  0  0  0  0]
 [ 0 10  0  0  0  0]
 [ 0  0  6  0  0  0]
 [ 0  0  0  4  0  0]
 [ 0  0  0  0  1  1]
 [ 0  0  0  0  0  3]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        10
           3       1.00      1.00      1.00         6
           5       1.00      1.00      1.00         4
           6       1.00      0.50      0.67         2
           7       0.75      1.00      0.86         3

    accuracy                           0.98        43
   macro avg       0.96      0.92      0.92        43
weighted avg       0.98      0.98      0.97        43



In [13]:
print("Evaluation of Model 3 RBF: ")
print(confusion_matrix(y_test, y_pred3))
print(classification_report(y_test, y_pred3))

Evaluation of Model 3 RBF: 
[[17  1  0  0  0  0]
 [ 0 10  0  0  0  0]
 [ 0  6  0  0  0  0]
 [ 0  1  0  0  0  3]
 [ 0  0  0  0  0  2]
 [ 0  0  0  0  0  3]]
              precision    recall  f1-score   support

           1       1.00      0.94      0.97        18
           2       0.56      1.00      0.71        10
           3       0.00      0.00      0.00         6
           5       0.00      0.00      0.00         4
           6       0.00      0.00      0.00         2
           7       0.38      1.00      0.55         3

    accuracy                           0.70        43
   macro avg       0.32      0.49      0.37        43
weighted avg       0.57      0.70      0.61        43



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
